### ISSUE TITLE
Unknown pixel format [ Test on Debian 8/GNU Linux ]

### ISSUE THREAD

**Issue by sparkecho** [TatriX/cl-sdl2-tutorial#1]
In **cl-sdl2-tutorial/2** it raises an error of  **Unknown pixel format**.  
(**Actually all the bmp images you supplied has this problem.**)

It's caused by the sample image **hello.bmp**, even use the original Lazy Foo's  C++ version source code, the same error was encountered.  

It works well with the origin image **hello_world.bmp** in Lazy Foo's tutorial. 
Though I don't know what's the real difference between your image and Lazy Foo's, but I hope that you can replace your picture with Lazy Foo's, also it would be nice if you can figure out what went wrong.

 (I do think it's related to the decode method of SDL.)

**Comment by TatriX** [comment]
Unfortunately I'm not interested in CL anymore. But it you want to send a PR feel free to do it. Thanks.

**Comment by sparkecho** [comment]
OK, I'll send pull request. Thanks for reply.
